- name: install chrome
  gather_facts: yes
  hosts: localhost
  tasks:
    - include_tasks: chrome.yaml
      when: "'chrome' in package_name"
    - include_tasks: adobe.yaml
      when: "'adobe' in package_name"

    
