- name: install chrome
  gather_facts: yes
  hosts: localhost
  tasks:
    - import_playbook: chrome.yaml
      when: "'chrome' in package_name"
    - import_playbook: adobe.yaml
      when: "'adobe' in package_name"

    
