- name: install chrome
  gather_facts: yes
  hosts: localhost
  tasks:
    - include_tasks: chrome.yaml
      when: "'chrome' in package_name"
    - include_tasks: adobe.yaml
      when: "'adobe' in package_name"
    - name: 
      lineinfile:
        path: /var/tmp/report.csv
        line: hostip,package,currentversion,installed version,upgraded,date
        create: yes
      delegate_to: 127.0.0.1
    - name: add entries in the csv file
      lineinfile:
        path: /var/tmp/report.csv
        line: "{{ host_ip }},chrome,{{ chrome_current_version | trim | default('not installed', true) }},{{ chrome_installer_version | trim  }},{{ upgrade_status | default('na') }},{{ ansible_date_time.date }}"
      delegate_to: 127.0.0.1
      when: "'chrome' in package_name"
    - name: add entries in the csv file
      lineinfile:
        path: /var/tmp/report.csv
        line: "{{ host_ip }},Adobe,{{ adobe_current_version | trim | default('not installed', true) }},{{ adobe_installer_version | trim  }},{{ upgrade_status | default('na') }},{{ ansible_date_time.date }}"
      delegate_to: 127.0.0.1
      when: "'adobe' in package_name"

    
